server.port: 8081
spring:
  data:
    mongodb:
      host:
        localhost
      port:
        27017
      database:
        db-v1-pagan-gods
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher